// <auto-generated />
using System;
using BlueModas.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlueModas.Infra.Data.Migrations
{
    [DbContext(typeof(BlueModasContext))]
    [Migration("20210815044253_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlueModas.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2debc054-b480-470d-a1d6-07106a705c61"),
                            CreatedAt = new DateTime(2021, 8, 15, 1, 42, 53, 654, DateTimeKind.Local).AddTicks(5682),
                            Description = "Camiseta de algodão macio",
                            Name = "Camiseta Branca",
                            UpdatedAt = new DateTime(2021, 8, 15, 1, 42, 53, 655, DateTimeKind.Local).AddTicks(2816)
                        },
                        new
                        {
                            Id = new Guid("829df3f6-2641-421e-a0de-e9f757337bc6"),
                            CreatedAt = new DateTime(2021, 8, 15, 1, 42, 53, 655, DateTimeKind.Local).AddTicks(3143),
                            Description = "Blusa de algodão macio",
                            Name = "Blusa Azul",
                            UpdatedAt = new DateTime(2021, 8, 15, 1, 42, 53, 655, DateTimeKind.Local).AddTicks(3147)
                        });
                });

            modelBuilder.Entity("BlueModas.Domain.Models.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");

                    b.HasData(
                        new
                        {
                            Id = new Guid("940b1a36-0fa2-40a6-b425-bd25144c82c2"),
                            CreatedAt = new DateTime(2021, 8, 15, 1, 42, 53, 657, DateTimeKind.Local).AddTicks(1502),
                            Location = "/images/products/image1.jpg",
                            ProductId = new Guid("2debc054-b480-470d-a1d6-07106a705c61"),
                            UpdatedAt = new DateTime(2021, 8, 15, 1, 42, 53, 657, DateTimeKind.Local).AddTicks(1511)
                        },
                        new
                        {
                            Id = new Guid("5398c5c5-4de2-4c15-8c27-4bfdf65fcd57"),
                            CreatedAt = new DateTime(2021, 8, 15, 1, 42, 53, 657, DateTimeKind.Local).AddTicks(1522),
                            Location = "/images/products/image1.jpg",
                            ProductId = new Guid("829df3f6-2641-421e-a0de-e9f757337bc6"),
                            UpdatedAt = new DateTime(2021, 8, 15, 1, 42, 53, 657, DateTimeKind.Local).AddTicks(1523)
                        });
                });

            modelBuilder.Entity("BlueModas.Domain.Models.ProductImage", b =>
                {
                    b.HasOne("BlueModas.Domain.Models.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlueModas.Domain.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
