// <auto-generated />
using System;
using BlueModas.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlueModas.Infra.Data.Migrations
{
    [DbContext(typeof(BlueModasContext))]
    [Migration("20210817015605_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlueModas.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("BlueModas.Domain.Models.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("BlueModas.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14a13698-82f8-4dd8-9728-391e419fa1f8"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 365, DateTimeKind.Local).AddTicks(3748),
                            ImagePath = "assets/images/image1.jpg",
                            Name = "Blusa de lã",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(321)
                        },
                        new
                        {
                            Id = new Guid("de9e7818-aaf9-48fa-b0b1-9581dc83a446"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(649),
                            ImagePath = "assets/images/image2.jpg",
                            Name = "Jaqueta de couro",
                            Price = 159.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(653)
                        },
                        new
                        {
                            Id = new Guid("e7507243-5e0a-4f03-819f-b4f241097156"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(656),
                            ImagePath = "assets/images/image3.jpg",
                            Name = "Blusa moletom",
                            Price = 39.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(656)
                        },
                        new
                        {
                            Id = new Guid("6f828370-7fce-4b54-af57-1e80508497f8"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(658),
                            ImagePath = "assets/images/image4.jpg",
                            Name = "Gorro para catioro",
                            Price = 24.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(659)
                        },
                        new
                        {
                            Id = new Guid("df079ab5-5f0e-4af9-9ee8-55b75a586066"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(661),
                            ImagePath = "assets/images/image5.jpg",
                            Name = "Camiseta branca",
                            Price = 19.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(662)
                        },
                        new
                        {
                            Id = new Guid("3131a6ac-9fc1-4f61-b3a6-8b2fa6e5615e"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(664),
                            ImagePath = "assets/images/image6.jpg",
                            Name = "Calça jeans",
                            Price = 69.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(665)
                        },
                        new
                        {
                            Id = new Guid("9f1c47b3-8961-4c44-8957-c02285490189"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(674),
                            ImagePath = "assets/images/image7.jpg",
                            Name = "Vestido vermelho",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(675)
                        },
                        new
                        {
                            Id = new Guid("5b617d3d-f40d-4930-86e1-9810838cd1f6"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(678),
                            ImagePath = "assets/images/image8.jpg",
                            Name = "Camisa",
                            Price = 54.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(678)
                        },
                        new
                        {
                            Id = new Guid("5d1ec522-114c-4520-9fd2-23982f413341"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(680),
                            ImagePath = "assets/images/image9.jpg",
                            Name = "Jaqueta jeans",
                            Price = 89.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(681)
                        },
                        new
                        {
                            Id = new Guid("68d248ac-5cd3-42f3-9d40-d3488f85f871"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(683),
                            ImagePath = "assets/images/image10.jpg",
                            Name = "Camiseta de manga longa",
                            Price = 25.00m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(684)
                        },
                        new
                        {
                            Id = new Guid("ca2f253a-7d3d-4834-a900-d4d438243d59"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(686),
                            ImagePath = "assets/images/image11.jpg",
                            Name = "Jaqueta de couro",
                            Price = 190.00m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(687)
                        },
                        new
                        {
                            Id = new Guid("a2a4ec6a-ba84-44f9-b950-83c14a87cc59"),
                            Active = false,
                            CreatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(688),
                            ImagePath = "assets/images/image12.jpg",
                            Name = "Vestido floral",
                            Price = 59.99m,
                            UpdatedAt = new DateTime(2021, 8, 16, 22, 56, 5, 366, DateTimeKind.Local).AddTicks(689)
                        });
                });

            modelBuilder.Entity("BlueModas.Domain.Models.OrderProduct", b =>
                {
                    b.HasOne("BlueModas.Domain.Models.Order", null)
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueModas.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlueModas.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
